language: node_js
node_js:
  - "stable"
script:
  - npm run build
deploy:
  provider: pages
  edge: true # For dpl v2 developer preview
  # skip_cleanup: true # This is default in dpl v2
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  # keep_history: true # This is default in dpl v2
  local_dir: build
  on:
    branch: master